### ISSUE TITLE
I want to value spacing at csstree 2.0.0

### ISSUE THREAD

**Issue by demonguyj** [csstree/csstree#173]
version: csstree 2.0.0

expected
```
border-bottom: 2px #f0f0f0 solid;
box-shadow: 0 -5px 5px 0 rgba(0, 0, 0, 0.05);
```

result
```
border-bottom: 2px#f0f0f0 solid;
box-shadow: 0-5px 5px 0 rgba(0, 0, 0, 0.05);
```

result works to modern browser.
But I unfortunately apply to IE11.
So I want to spacing to values.

How can I do this??

Help me please.

Thanks :)

**Comment by lahmatiy** [comment]
The generator's `mode: 'safe'` exists because of IE11 ;)
I didn't test much in IE11. so some fixes might be missed. I tested your examples, my results: `border` is broken, but `box-shadow` works well. Going to add whitespace between dimension and hash.

**Comment by demonguyj** [comment]
Thanks for your check.
But I found some cases.
So I share for you.
Thanks :)

Expected
```
background-position: 5% 90%, 10% 90%, 10% 90%, 15% 90%, 25% 90%, 25% 90%, 40% 90%, 55% 90%, 70% 90%;
margin: 0 0 0 -15px;
```

Result
```
background-position: 5%90%, 10%90%, 10%90%, 15%90%, 25%90%, 25%90%, 40%90%, 55%90%, 70%90%;
margin: 0 0 0-15px;
```

**Comment by lahmatiy** [comment]
All these cases are valid in IE11 (except `border` I mentioned before)
![image](https://user-images.githubusercontent.com/270491/145411054-d154a7f4-46de-49ed-8b74-8323bb97a1a2.png)
Do you have different results?

**Comment by demonguyj** [comment]
I have a same result too.
I just check difference from before version.
:)

**Comment by lahmatiy** [comment]
I added tests for this part (that's very complicated that's why I didn't it before). I also tested in IE11 and more cases are covered now. As a result, I fixed several issues in css-tree and one [minor bug in spec](https://github.com/w3c/csswg-drafts/pull/6874) :) So now this part is more stable.

**Comment by lahmatiy** [comment]
Fixes are released in [2.0.2](https://github.com/csstree/csstree/releases/tag/v2.0.2)

**Comment by demonguyj** [comment]
Unfortunately I still broken border. :(
Check it please.... 


expected
```
border-bottom: 2px #f0f0f0 solid;
```

result
```
border-bottom: 2px#f0f0f0 solid;
```

**Comment by lahmatiy** [comment]
Do you use `2.0.3`? I will check as well as will check for the tests to cover it

**Comment by demonguyj** [comment]
I just tested csso 5.0.1. 
I knew csso 5.0.1 into csstree 2.0.3.

**Comment by lahmatiy** [comment]
Fixed in CSSTree [2.0.4](https://github.com/csstree/csstree/releases/tag/v2.0.4) / CSSO [5.0.2](https://github.com/css/csso/releases/tag/v5.0.2)
